### ISSUE TITLE
Any plans to support context being passed through?

### ISSUE THREAD

**Issue by speza** [recurly/recurly-client-go#54]
Hi,

Are there any plans to support context being passed through? 

Something like this would be great:
```
GetSubscription(subscriptionId string) (*Subscription, error)
GetSubscriptionCtx(ctx context.Context, subscriptionId string) (*Subscription, error)
```

Edit:

So I noticed you can set it on anything that has an object composed of `Params` passed in...
```
ListSubscriptions(params *ListSubscriptionsParams) *SubscriptionList
```
But a lot of endpoints have no way to set the context.

Thanks
Sam

**Comment by douglasmiller** [comment]
Hey @speza, sorry for the delayed response on this.

We are considering this as a feature for the next major version of the client, `4.x`, as it would be a breaking change to introduce to the current major version, `3.x`.

**Comment by speza** [comment]
@douglasmiller could you not introduce new ClientInterface methods to remain compatible? (e.g. `GetSubscriptionCtx(...)`)

**Comment by speza** [comment]
@douglasmiller any updates on this?

I'm not looking to utilise the context just for cancellation. I'm also looking to instrument recurly-client-go with distributed tracing using the `http.RoundTripper`. Problem I have is that I need to derive a child span off the parent http request span. This isn't going to be possible right now as the parent span is within the context which cannot be passed through.

**Comment by douglasmiller** [comment]
@speza there's a [work in progress pull request open](https://github.com/recurly/recurly-client-go/pull/69) for the current 3.x client that will make it possible to pass a context to each operation.

We are still making small revisions and adding testing around the changes, but the core concept is pretty complete. Feel free to review and make any comments there.

The general idea is that you can add `WithContext()`, and others, to any of the operations.

**Comment by speza** [comment]
This sounds positive @douglasmiller! Just took a quick look. This would definitely work :+1:

**Comment by douglasmiller** [comment]
Hey @speza 

We ended up adding `WithContext` variants of each operation in the client (with context as the first parameter). You can review the previously linked pull request description for more details.

This was released yesterday afternoon. Thank you for your patience on this as we needed to address some other issues alongside the inclusion of the context. Let me know if you have any issues or questions.
