### ISSUE TITLE
FetchWithContext not exposed within ClientInterface

### ISSUE THREAD

**Issue by abMatillion** [recurly/recurly-client-go#77]
FetchWithContext is not exposed within ClientInterface so it's difficult to mock the implementation of ListUsages

**Comment by speza** [comment]
I think the issue here is that methods such as `FetchWithContext` return a concrete implementation. It would be better to return an interface e.g. 

```
type UsageLister interface {
	FetchWithContext(ctx context.Context) error
	CountWithContext(ctx context.Context) (*int64, error)
	HasMore() bool
	Data() []Usage
	...
}
```

**Comment by douglasmiller** [comment]
Hey @abMatillion and @speza, thanks for letting us know about this. 

I think that returning an interface from these functions makes sense and will make it easier to test against. I'm not sure that we'll be able to make this kind of change in the 3.x version of the client, though, as it would be a breaking change.

We will look into getting this included into the next major version of the client, which we hope to be releasing this quarter. I'll leave the issue open to keep you updated.

**Comment by speza** [comment]
Thanks @douglasmiller, that's understandable. We have a workaround which isn't _too_ bad. We've basically extended the recurly.ClientInterface to have a `ListUsageExt(...) UsageLister` method which wraps the standard ListUsage method.

**Comment by douglasmiller** [comment]
@speza / @abMatillion We just merged #80 which will include an interface for the List* methods. As previously mentioned, this will be for the 4.x version of the client.

Thanks again for all of the great feedback and critique on this client library!

**Comment by speza** [comment]
Thank you @douglasmiller, happy to feedback! Just out of interest, when is v4 likely to be released?

**Comment by douglasmiller** [comment]
We are targeting end of February
